server.port=8081

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

#spring.sql.init.mode=never

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=3600000

spring.task.scheduling.enabled=true
parking.scheduler.fixedRate=60000